create method getFrentes
AcompanhaLegis/sdk-dados-abertos-camara-js pull request #16
Opened 2020-10-01 16:57 UTC by LeonardoCamargo31

Create method getFrentes.

Usage:
```js
await CamaraAPI.getFrentes({idLegislatura:'56'})
await CamaraAPI.getFrentes()
```

2020-10-01 19:38 UTC, kimuraz requested changes
:1st_place_medal: Nice job! Please, check my comments, almost there! :+1:

2020-10-01 19:38 UTC, kimuraz commented on modules/frentes.js
> +export const getFrentes= async (
Nice job here!

I just miss the `getFrente`  which wraps `/frentes/{id}` and the ` getFrenteMembros` (`/frentes/{id}/membros`), so to fulfill the issue, can you add those here?

2020-10-01 19:38 UTC, kimuraz commented on sample.js
> +  console.log('frentesParlamentar', frentesParlamentar);
:+1:

2020-10-01 19:41 UTC, LeonardoCamargo31 commented on modules/frentes.js
> +export const getFrentes= async (
okay, I will create these methods ;)

2020-10-04 12:10 UTC, kimuraz approved these changes
nice job! 🚀

2020-10-04 12:10 UTC, merged