Feature/lint
AcompanhaLegis/sdk-dados-abertos-camara-js pull request #20
Opened 2020-10-03 18:02 UTC by LeonardoCamargo31

Desculpe se estiver quebrando alguma regra de contribuição, pois nem criei uma issue sobre o assunto.

Esses dias criei uma PR e ela estava quebrado, pois eu deveria executar o script `npm run format`, e passar no prettier.

Bom basicamente adicionei a biblioteca `eslint` para ter um padrão de código.

E o husky, para executar o `eslint` antes de qualquer commit.

2020-10-04 21:00 UTC, kimuraz commented
@LeonardoCamargo31 O ideal seria abrir a issue, mas muito obrigado pela iniciativa!

Eu vou revisar as alterações durante essa semana, mas eu tenho alguma resitência com o Husky haha eu acho que já temos coisas como o git hook pra isso que não necessitam de instalação e pode ter uma configuração bem personalizada, vou olhar a evolução disso e vou comentar por aqui!

2020-10-06 17:57 UTC, kimuraz requested changes
:1st_place_medal: Excelente trabalho! Muito obrigado pela contribuição!

Bom, eu e o @alexandreab discutimos sobre as configurações no .editorconfig e do husky, e a conclusão que chegamos é que essas são ferramentas pessoais e não devemos incluir no projeto, pq isso impõe o uso das ferramentas para todas as pessoas. Então acho que seria válido retirar os commits que incluem o `husky` (e arquivos relacionados) e o `.editorconfig`. Quando as modificações forem feitas e a branch tiver atualizada, podemos fazer `merge`! Muito obrigado mais uma vez! :+1:

2020-10-06 22:11 UTC, LeonardoCamargo31 commented
Muito obrigado pela atenção @kimuraz :punch:

Sim faz sentido esse ponto de vista, gosto do husky, principalmente para executar o eslint assim como testes e etc, e nem deixar commitar algo quebrado.

Vou criar uma PR e fechar essa, pode ser?

2020-10-07 17:19 UTC, BrunaNayara commented
@LeonardoCamargo31 Você pode atualizar a branch com a master e resolver os conflitos, por favor?

2020-10-07 20:40 UTC, closed without merging