Add wrapper for /orgaos endpoint
AcompanhaLegis/sdk-dados-abertos-camara-js pull request #22
Opened 2020-10-06 16:04 UTC by tfbbueno

2020-10-06 17:51 UTC, BrunaNayara commented
Olá @tfbbueno Obrigada pelo PR. 
Pedi pro @kimuraz revisar direitinho. 

Mas você pode dar uma olhadinha nesses dois pontos, por favor:
- Atualizar a sua branch com a master 
- Ver o check que falhou (acho que foi só formatação)

2020-10-06 18:40 UTC, kimuraz requested changes
:1st_place_medal: Ótimo trabalho! Muito obrigado pela contribuição!

Deixei alguns comentários, assim que a branch estiver atualizada e os cometários resolvidos podemos fazer o merge!

2020-10-06 18:40 UTC, kimuraz commented on modules/orgaos.js
> +export const getOrgaoEventos = async (
Os endpoints de evento são um pouco diferentes dos demais (talvez algum outro seja parecido, mas não me recordo agora), porque os endpoints `nested` também possuem alguns campos de ordenação e filtro... Como por exemplo esse de eventos:

```
id
idTipoEvento
dataInicio
dataFim
``` 
Mas isso também acontece para os endpoints de membros e votações dentro de `orgaos`. O projeto não tem um CONTRIBUTING.md explicando exatamente como fazê-lo, então é culpa nossa (mantenedores). Então se quiser deixar para uma próxima contribuição ou para outra pessoa, vamos abrir uma issue para adicionar esses parâmetro depois, caso contrário só fazer a modificação nesse mesmo PR :+1: 

> PS: Vou adicionar o CONTRIBUTING.md com nossas práticas e guidelines para adicionar endpoints!

2020-10-06 18:40 UTC, kimuraz commented on modules/orgaos.js
> +    'dataInicio',
@tfbbueno os itens: `pagina, itens, ordem e ordenarPor` já estão como "default" no nosso arquivo de validação :smiley: 

Então acho que podem ser retirados aqui e  :grimacing:

2020-10-06 18:40 UTC, kimuraz commented on modules/orgaos.js
> +  const availableOrderFields = [
@tfbbueno Aqui, de acordo com a documentação da API, os campos para ordenação são:
```
id, sigla, nome, apelido, codTipoOrgao, tipoOrgao, dataInicio ou dataFim
```

2020-10-07 20:46 UTC, kimuraz approved these changes
🚀 Muito obrigado!

2020-10-07 20:48 UTC, merged